version: "3.3"
networks:
  monitor:
    driver: bridge
services:
  grafana:
    restart: always
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - $PWD/grafana:/var/lib/grafana/
    networks:
      - monitor
    user: "$UID:$GID"
  loki:
    image: grafana/loki:2.1.0
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
    networks:
      - monitor
  promtail:
      image: grafana/promtail:latest
      container_name: promtail
      restart: unless-stopped
      volumes:
        - /home/steven/.local/share/docker/containers/fb1db74b1fb5d9b5e5c983f0dfba3e881ad57c4583948b631d32a4c0ac226b77:/var/log/graphnode
        - /home/steven/.local/share/docker/containers/42a296d9b81b58d1ac61f6d058f903a4ad7108bcc1d41c7b3608192297d0e391:/var/log/go-u2u
        - /home/steven/.local/share/docker/containers/473aaf11297ee89ed8bc5f1c222411c5cadba9daabba560548b6588099d4aa62:/var/log/go-kardia
        - ./promtail-config.yaml:/etc/promtail/config.yml
      command: -config.file=/etc/promtail/config.yml
      networks:
        - monitor
