version: "3.3"
networks:
  monitor:
    driver: bridge
services:
  grafana:
    restart: always
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - $PWD/grafana:/var/lib/grafana/
    networks:
      - monitor
    user: "$UID:$GID"
  loki:
    image: grafana/loki:2.1.0
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
    networks:
      - monitor
  promtail:
      image: grafana/promtail:latest
      container_name: promtail
      restart: unless-stopped
      volumes:
        - /home/steven/.local/share/docker/containers/264872086aa79b5b1869ce28b460a04d1d82e119e41d396cbf0aadcbb39b73f0:/var/log/demo
        - ./promtail-config.yaml:/etc/promtail/config.yml
      command: -config.file=/etc/promtail/config.yml
      networks:
        - monitor
